hook:
  slug: OPP
  name: Opportunity Knocks
  description: |
    <h4>Opportunity Knocks</h4>
    Please see page 37 of the Core Rulebook for details.
hook:
  slug: HIGH
  name: Higher Calling
  description: |
    <h4>Higher Calling</h4>
    Please see page 37 of the Core Rulebook for details.
hook:
  slug: ENEMIES
  name: Enemies and Antagonists
  description: |
    <h4>Enemies and Antagonists</h4>
    Please see page 38 of the Core Rulebook for details.
hook:
  slug: FLAW
  name: Failure of Character
  description: |
    <h4>Failure of Character</h4>
    Please see page 38 of the Core Rulebook for details.
hook:
  slug: WRONG
  name: Wrong Place, Wrong Time
  description: |
    <h4>Wrong Place, Wrong Time</h4>
    Please see page 38 of the Core Rulebook for details.
hook:
  slug: ACADEMIC
  name: Academic
  description: |
    <h4>Academic</h4>
    Please see page 13 of Enter the Unknown for details.

  source: Enter the Unknown
hook:
  slug: CRIMINAL
  name: Criminal
  description: |
    <h4>Criminal</h4>
    Please see page 13 of Enter the Unknown for details.

  source: Enter the Unknown
hook:
  slug: ENTREPRENEUR
  name: Entrepreneur
  description: |
    <h4>Entrepreneur</h4>
    Please see page 15 of Enter the Unknown for details.

  source: Enter the Unknown
hook:
  slug: EXIMP
  name: Ex-Imperial Operator
  description: |
    <h4>Ex-Imperial Operator</h4>
    Please see page 16 of Enter the Unknown for details.

  source: Enter the Unknown

hook:
  slug: FALLENNOBLE
  name: Fallen Noble
  description: |
    <h4>Fallen Noble</h4>
    Please see page 16 of Enter the Unknown for details.

  source: Enter the Unknown

hook:
  slug: WANDERER
  name: Wanderer
  description: |
    <h4>Wanderer</h4>
    Please see page 18 of Enter the Unknown for details.

  source: Enter the Unknown

