down_and_out:
  slug: "OUT"
  name: "Down and Out"
  description: |
    <h4>Down and Out</h4>
    <p>Please see page 36 of the Edge of the Empire Core Rulebook for details.</p>
middle_class_struggles:
  slug: "MIDDLE"
  name: "Middle Class Struggles"
  description: |
    <h4>Middle Class Struggles</h4>
    <p>Please see page 37 of the Edge of the Empire Core Rulebook for details.</p>
high_and_mighty:
  slug: "HIGH"
  name: "High and Mighty"
  description: |
    <h4>High and Mighty</h4>
    <p>Please see page 37 of the Edge of the Empire Core Rulebook for details.</p>
the_outsider:
  slug: "OUT"
  name: "The Outsider"
  description: |
    <h4>The Outsider</h4>
    <p>Please see page 37 of the Edge of the Empire Core Rulebook for details.</p>
