bothan:
  name: "Bothan"
  brawn: 1
  agility: 2
  intellect: 2
  cunning: 3
  willpower: 2
  presence: 2
  unused_xp: 100
  wound_threshold_modifier: 10
  strain_threshold_modifier: 11
  starting_skills:
    - "Streetwise"

droid:
  name: "Droid"
  brawn: 1
  agility: 1
  intellect: 1
  cunning: 1
  willpower: 1
  presence: 1
  unused_xp: 175
  wound_threshold_modifier: 10
  strain_threshold_modifier: 10


gand:
  name: "Gand"
  brawn: 2
  agility: 2
  intellect: 2
  cunning: 2
  willpower: 3
  presence: 1
  unused_xp: 100
  starting_skills:
    - "Discipline"
  wound_threshold_modifier: 10
  strain_threshold_modifier: 10

human:
  name: "Human"
  brawn: 2
  agility: 2
  intellect: 2
  cunning: 2
  willpower: 2
  presence: 2
  unused_xp: 110
  optional_skills_count: 2
  optional_skills:
    - "all"
  wound_threshold_modifier: 10
  strain_threshold_modifier: 10

rodian:
  name: "Rodian"
  brawn: 2
  agility: 3
  intellect: 2
  cunning: 2
  willpower: 1
  presence: 2
  unused_xp: 100
  starting_skills:
    - "Survival"
  wound_threshold_modifier: 10
  strain_threshold_modifier: 10

trandoshan:
  name: "Trandoshan"
  brawn: 3
  agility: 1
  intellect: 2
  cunning: 2
  willpower: 2
  presence: 2
  unused_xp: 90
  wound_threshold_modifier: 12
  strain_threshold_modifier: 9
  starting_skills:
    - "Perception"

twilek:
  name: "Twi'lek"
  brawn: 1
  agility: 2
  intellect: 2
  cunning: 2
  willpower: 2
  presence: 3
  unused_xp: 100
  wound_threshold_modifier: 10
  strain_threshold_modifier: 11
  optional_skills_count: 1
  optional_skills:
    - "Charm"
    - "Deception"

wookiee:
  name: "Wookiee"
  brawn: 3
  agility: 2
  intellect: 2
  cunning: 2
  willpower: 1
  presence: 2
  unused_xp: 90
  wound_threshold_modifier: 14
  strain_threshold_modifier: 8
  starting_skills:
    - "Brawl"
